### ISSUE TITLE
link of Probase can't be reached

### ISSUE THREAD

**Issue by WilliamsToTo** [HKUST-KnowComp/atomic-conceptualization#2]
I found the link to Probase doesn't work.
The website you give is `http://concept.research.microsoft.com/Home/Download`, but it shows:

This site can’t be reached
- concept.research.microsoft.com took too long to respond.
- Try:
  - Checking the connection
  - [Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
 
ERR_CONNECTION_TIMED_OUT

**Comment by zhaowei-wang-nlp** [comment]
Hi WilliamsToTo,
We update a copy of Probase in the readme in this repo. Please note that all licenses are subject to MSRA's original release.
https://github.com/HKUST-KnowComp/atomic-conceptualization/blob/main/README.md
